GET http://localhost:3000/posts
###

POST http://localhost:3000/posts HTTP/1.1
content-type: application/json

{
    "title": "This is the tile",
    "description": "This is the description"
}

### REST client for VS Code